li_listing_class: css-p74l73 es62z2j19
estate_title_tag_class: css-1sfzh0a eu6swcv20
estate_details_tag_class: css-1wi2w6s estckra5
estate_price_tag_class: css-8qi9av eu6swcv19
estate_location_tag_class: e1nbpvi60 css-171pgf6 e1enecw71